import type { CaseDetail, InvestigationReport } from "@shared/types";
import { buildDecision } from "./decisionEngine.js";

const DISCLAIMER =
  "This is a prototype investigation report generated by SentinelX AI's Mock Intelligence Engine. " +
  "All detections are produced by deterministic, rule-based heuristics over a scripted demo scenario — " +
  "no real telephony data, live surveillance, or machine-learning inference was used. For demonstration " +
  "and evaluation purposes only; not admissible as evidence.";

function buildIncidentSummary(caseDetail: CaseDetail): string {
  return (
    `On ${new Date(caseDetail.startedAt).toLocaleString("en-IN")}, a subject identified as "${caseDetail.victimAlias}" ` +
    `in ${caseDetail.city}, ${caseDetail.state} received a call from an individual impersonating ${caseDetail.impersonatedAuthority}. ` +
    `Over the course of the interaction, the Mock Intelligence Engine detected ${caseDetail.reasons.length} distinct threat ` +
    `signal(s), escalating the case to a final threat score of ${caseDetail.finalScore}/100 (${caseDetail.threatLevel.toUpperCase()}). ` +
    `The case was ${caseDetail.status} after a duration of approximately ${Math.round(caseDetail.durationMs / 60000)} minute(s).`
  );
}

function buildEvidence(caseDetail: CaseDetail): string[] {
  return caseDetail.reasons.map((reason) => {
    const line = caseDetail.transcript.find((t) => t.id === reason.transcriptLineId);
    const speaker = line ? line.speaker.toUpperCase() : "UNKNOWN";
    return `[${speaker}] "${reason.matchedPhrase}" — ${reason.explanation}`;
  });
}

export function buildInvestigationReport(caseDetail: CaseDetail): InvestigationReport {
  const decision = buildDecision(caseDetail.id, caseDetail.threatLevel, caseDetail.durationMs);

  return {
    caseId: caseDetail.id,
    generatedAt: new Date().toISOString(),
    title: caseDetail.title,
    incidentSummary: buildIncidentSummary(caseDetail),
    impersonatedAuthority: caseDetail.impersonatedAuthority,
    victimAlias: caseDetail.victimAlias,
    city: caseDetail.city,
    state: caseDetail.state,
    finalScore: caseDetail.finalScore,
    threatLevel: caseDetail.threatLevel,
    timeline: caseDetail.timeline,
    evidence: buildEvidence(caseDetail),
    indicators: caseDetail.reasons,
    recommendations: decision.actions,
    disclaimer: DISCLAIMER,
  };
}
