import type { CaseDetail, InvestigationReport } from "@shared/types";

const DISCLAIMER =
  "This investigation report was generated by SentinelX AI from a real registered case " +
  "(live mic session, uploaded recording, chat screenshot, or manual entry). Threat scores " +
  "combine a deterministic keyword/rule engine with an optional LLM second opinion. " +
  "For operational review — not a substitute for lawful telecom CDR requests or court process.";

function buildIncidentSummary(caseDetail: CaseDetail): string {
  const durationLabel =
    caseDetail.durationMs >= 60_000
      ? `${Math.round(caseDetail.durationMs / 60000)} minute(s)`
      : `${Math.round(caseDetail.durationMs / 1000)} second(s)`;

  return (
    `On ${new Date(caseDetail.startedAt).toLocaleString("en-IN")}, a subject identified as "${caseDetail.victimAlias}" ` +
    `in ${caseDetail.city}, ${caseDetail.state} was involved in an interaction analyzed as ` +
    `${caseDetail.title} (source: ${caseDetail.source ?? "unknown"}). ` +
    `The engine detected ${caseDetail.reasons.length} distinct threat signal(s), with a final threat score of ` +
    `${caseDetail.finalScore}/100 (${caseDetail.threatLevel.toUpperCase()}). ` +
    `Case status: ${caseDetail.status === "live" ? "ONGOING" : caseDetail.status.toUpperCase()}. ` +
    `Evidence duration approximately ${durationLabel}.` +
    (caseDetail.notes ? ` Notes: ${caseDetail.notes}` : "") +
    (caseDetail.resolution
      ? ` Resolution by ${caseDetail.resolution.resolvedByName}: ${caseDetail.resolution.notes}`
      : "")
  );
}

function buildEvidence(caseDetail: CaseDetail): string[] {
  const items: string[] = [];

  if (caseDetail.recordingUrl) {
    if (caseDetail.recordingUrl.startsWith("data:")) {
      const approxKb = Math.round((caseDetail.recordingUrl.length * 3) / 4 / 1024);
      items.push(
        `Audio evidence attached (inline copy, ~${approxKb} KB) — play it in Historical Cases / Investigation Replay. Not pasted as raw base64 into this PDF.`,
      );
    } else if (caseDetail.recordingUrl.startsWith("blob:")) {
      items.push(
        "Audio evidence was only available as a temporary browser blob URL (not persisted). Re-record and ensure Firebase Storage rules for recordings/ are published.",
      );
    } else {
      items.push(`Audio evidence stored at: ${caseDetail.recordingUrl}`);
    }
  }

  if (caseDetail.evidenceImageUrl) {
    if (caseDetail.evidenceImageUrl.startsWith("data:")) {
      items.push("Chat screenshot evidence attached (embedded image in this report when available).");
    } else {
      items.push(`Screenshot evidence stored at: ${caseDetail.evidenceImageUrl}`);
    }
  }

  for (const reason of caseDetail.reasons) {
    const line = caseDetail.transcript.find((t) => t.id === reason.transcriptLineId);
    const speaker = line ? line.speaker.toUpperCase() : "UNKNOWN";
    const phrase = reason.matchedPhrase.length > 120 ? `${reason.matchedPhrase.slice(0, 117)}...` : reason.matchedPhrase;
    items.push(`[${speaker}] "${phrase}" — ${reason.explanation}`);
  }

  if (items.length === 0) {
    items.push("No structured threat indicators captured — review the full transcript timeline.");
  }
  return items;
}

function buildRecommendations(caseDetail: CaseDetail): string[] {
  if (caseDetail.threatLevel === "critical" || caseDetail.threatLevel === "high") {
    return [
      "Keep this case ONGOING until an officer explicitly marks it complete",
      "Trigger citizen advisories — do not transfer money or share OTP",
      "Alert bank / UPI risk teams if payment channels were mentioned",
      "File on cybercrime.gov.in / dial 1930 for lawful CDR pull",
      "Preserve audio/screenshot evidence attached to this case record",
    ];
  }
  if (caseDetail.threatLevel === "elevated") {
    return [
      "Monitor for further contact from the same number or UPI handle",
      "Verify any claimed officer identity via the Officer Registry",
      "Report to authorities if money transfer is demanded",
    ];
  }
  return [
    "Low threat — retain the record if registered, no urgent escalation required",
    "Re-run analysis if new evidence appears",
  ];
}

/** Builds a PDF-ready report from any CaseDetail — works for real Firebase cases, not only mock demos. */
export function buildInvestigationReportFromCase(caseDetail: CaseDetail): InvestigationReport {
  return {
    caseId: caseDetail.id,
    generatedAt: new Date().toISOString(),
    title: caseDetail.title,
    incidentSummary: buildIncidentSummary(caseDetail),
    impersonatedAuthority: caseDetail.impersonatedAuthority,
    victimAlias: caseDetail.victimAlias,
    city: caseDetail.city,
    state: caseDetail.state,
    finalScore: caseDetail.finalScore,
    threatLevel: caseDetail.threatLevel,
    timeline: caseDetail.timeline,
    evidence: buildEvidence(caseDetail),
    evidenceImageUrl: caseDetail.evidenceImageUrl,
    indicators: caseDetail.reasons,
    recommendations: buildRecommendations(caseDetail),
    disclaimer: DISCLAIMER,
  };
}
